### ISSUE TITLE
Add to FreeCAD addons ?

### ISSUE THREAD

**Issue by luzpaz** [hstarmans/freecad_hexastorm#1]
Are you interested?  
If so, feel free to discuss on the forum.freecad.org  
Also there needs to be a [metadata](https://wiki.freecadweb.org/Package_Metadata)

**Comment by hstarmans** [comment]
@luzpaz , thank you for your time and your contributions to FreeCAD. It has been very helpful.
 This module is now a very custom script just for my [prism scanner](https://youtu.be/dR09Tev0cPk).
I am now working on simplifying and reducing the cost of the design of the prism scanner.  The module is not really useful to others. It can only be used for prism scanners and I am the only one who has a working one (except for the Dutch government / AMSytems).
